"""Combine recognizer per-letter probabilities with the char-LM to recommend
the best spelling for each word.

    score(candidate) = P_rec(candidate) * P_lm(candidate)^alpha

where P_rec = product of the recognizer's probability for each of the
candidate's letters at its position, and P_lm = exp(context log-likelihood)
from the char-LM. Candidate spellings are generated by swapping confusion
neighbours into a letter position, but only where the swapped-in letter is in
the recognizer's per-position top-K (so we respect handwriting evidence).

A suggestion is surfaced only when the best non-greedy spelling beats the
recognizer's greedy spelling by SUGGEST_MARGIN (in log space).
"""

import math

import confusions as conf
import context_lm

ALPHA = 1.0            # LM weight in the combine (P_lm^alpha)
SUGGEST_MARGIN = 0.15  # min log-score margin to surface a suggestion
TOP_K = 5


def _log_rec(candidate: str, per_letter_probs) -> float:
    """Recognizer log-prob for a candidate spelling (log of product).

    per_letter_probs: list of dicts {letter: prob} per char position.
    """
    logp = 0.0
    for pos, letter in enumerate(candidate):
        p = per_letter_probs[pos].get(letter, 0.0)
        if p <= 0.0:
            return -1e9
        logp += math.log(p)
    return logp


def _log_lm(candidate: str, sentence: str, ws: int, we: int) -> float:
    return context_lm.score_candidate(sentence, ws, we, candidate)


def combine_log_score(candidate: str, sentence: str, ws: int, we: int,
                      per_letter_probs, alpha: float = ALPHA) -> float:
    """Combined log score: log P_rec + alpha * log P_lm."""
    return _log_rec(candidate, per_letter_probs) + alpha * _log_lm(
        candidate, sentence, ws, we)


def greedy_spelling(per_letter_probs) -> str:
    """Argmax recognizer letter at each position."""
    return "".join(max(pos, key=pos.get) for pos in per_letter_probs)


def candidate_spellings(greedy: str, per_letter_probs,
                        top_k: int = TOP_K) -> list[str]:
    """All single-letter swaps of a confusion neighbour into a position where
    the neighbour is in the recognizer's per-position top-K.

    Returns distinct candidates (excludes the greedy spelling itself).
    """
    cands: set[str] = set()
    for pos_idx, pos in enumerate(per_letter_probs):
        topk = set(pos.keys())
        if len(pos) > top_k:
            topk = set(list(pos)[:top_k])
        letter = greedy[pos_idx]
        for nb in conf.neighbours(letter):
            if nb in topk:
                cands.add(greedy[:pos_idx] + nb + greedy[pos_idx + 1:])
    return list(cands)


def recommend(sentence: str, ws: int, we: int, per_letter_probs,
              alpha: float = ALPHA, margin: float = SUGGEST_MARGIN,
              top_k: int = TOP_K) -> dict:
    """Pick the best spelling for the word at [ws, we) in `sentence`.

    per_letter_probs: list of {letter: prob} per char position of the word.

    Returns {"best": str, "alternatives": [str,...], "margin": float} where
    `best` is the combined-score winner. If `best` differs from the recognizer
    greedy spelling and the log-margin >= `margin`, a suggestion is surfaced
    (caller decides). Always returns the winning spelling (greedy if no swap
    wins).
    """
    greedy = greedy_spelling(per_letter_probs)
    if len(per_letter_probs) == 0:
        return {"best": greedy, "alternatives": [], "margin": 0.0}

    # ensure the greedy spelling has non-zero recognizer prob (dict is top-K,
    # so the argmax is always present)
    best = greedy
    best_score = combine_log_score(greedy, sentence, ws, we,
                                   per_letter_probs, alpha)
    alternatives = []

    for cand in candidate_spellings(greedy, per_letter_probs, top_k):
        sc = combine_log_score(cand, sentence, ws, we, per_letter_probs, alpha)
        if sc > best_score:
            best_score = sc
            best = cand

    margin = best_score - combine_log_score(
        greedy, sentence, ws, we, per_letter_probs, alpha)
    alternatives = [c for c in candidate_spellings(greedy, per_letter_probs,
                                                   top_k) if c != best]
    return {"best": best, "alternatives": alternatives, "margin": margin}


def should_surface(result: dict, margin: float = SUGGEST_MARGIN,
                   greedy: str | None = None) -> bool:
    if greedy is None:
        greedy = result.get("_greedy", "")
    return result["best"] != greedy and result["margin"] >= margin


def recommend_all(per_letter_probs_list: list[dict],
                  x_boxes: list[tuple[int, int]],
                  alpha: float = ALPHA, margin: float = SUGGEST_MARGIN,
                  top_k: int = TOP_K) -> dict:
    """Run the full recommendation pipeline over all recognized components.

    Groups components into words by x-gap, builds the sentence from each word's
    greedy recognizer spelling, then recommends a spelling for every word.

    per_letter_probs_list: one {letter: prob} dict per component (ordered).
    x_boxes: per-component (x0, x1) in logical px.

    Returns {"sentence": str, "words": [{"spelling","best","alternatives",
    "margin","offsets"}]}.
    """
    import recognizer as rec
    greedy_flat = "".join(max(pos, key=pos.get) for pos in per_letter_probs_list)
    groups = rec.group_words(x_boxes)
    word_spellings: list[str] = []
    word_probs: list[list[dict]] = []
    for g in groups:
        probs = [per_letter_probs_list[i] for i in g]
        word_probs.append(probs)
        word_spellings.append("".join(max(pos, key=pos.get) for pos in probs))
    sentence, offsets = rec.build_sentence_and_offsets(word_spellings)

    words: list[dict] = []
    for wi, g in enumerate(groups):
        probs = [per_letter_probs_list[i] for i in g]
        ws, we = offsets[wi]
        r = recommend(sentence, ws, we, probs, alpha=alpha, margin=margin,
                      top_k=top_k)
        r["_greedy"] = word_spellings[wi]
        words.append({
            "spelling": word_spellings[wi],
            "best": r["best"],
            "alternatives": r["alternatives"],
            "margin": r["margin"],
            "offsets": [ws, we],
            "indices": list(g),
        })
    return {"sentence": sentence, "words": words,
            "greedy_flat": greedy_flat}